/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 06-oct-2025 15:56:30 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Asignatura]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inscripcion] DROP CONSTRAINT [FK_Asignatura]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Alumno]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Inscripcion] DROP CONSTRAINT [FK_Alumno]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Alumno]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Alumno]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Asignatura]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Asignatura]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Inscripcion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Inscripcion]
GO

/* Create Tables */

CREATE TABLE [Alumno]
(
	[cif] nvarchar(9) NOT NULL,
	[nombre] nvarchar(60) NULL
)
GO

CREATE TABLE [Asignatura]
(
	[cod] int NOT NULL,
	[horario] nvarchar(30) NULL,
	[nombre] nvarchar(50) NULL
)
GO

CREATE TABLE [Inscripcion]
(
	[cod] int NOT NULL,
	[cif] nvarchar(9) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Alumno] 
 ADD CONSTRAINT [PK_Alumno]
	PRIMARY KEY CLUSTERED ([cif] ASC)
GO

ALTER TABLE [Asignatura] 
 ADD CONSTRAINT [PK_Asignatura]
	PRIMARY KEY CLUSTERED ([cod] ASC)
GO

ALTER TABLE [Inscripcion] 
 ADD CONSTRAINT [PK_Inscripcion]
	PRIMARY KEY CLUSTERED ([cod] ASC,[cif] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Inscripcion] ADD CONSTRAINT [FK_Asignatura]
	FOREIGN KEY ([cod]) REFERENCES [Asignatura] ([cod]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Inscripcion] ADD CONSTRAINT [FK_Alumno]
	FOREIGN KEY ([cif]) REFERENCES [Alumno] ([cif]) ON DELETE No Action ON UPDATE No Action
GO
