/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 29-sept-2025 16:11:16 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Estudiante_Expediente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Expediente] DROP CONSTRAINT [FK_Estudiante_Expediente]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estudiante]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estudiante]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Expediente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Expediente]
GO

/* Create Tables */

CREATE TABLE [Estudiante]
(
	[cif] varchar(50) NOT NULL,
	[nombres] nvarchar(50) NULL,
	[apellidos] nvarchar(50) NULL
)
GO

CREATE TABLE [Expediente]
(
	[num] int NOT NULL IDENTITY (1, 1),
	[fechaNac] date NULL,
	[direccion] varchar(max) NULL,
	[fechaIngreso] date NULL,
	[cif] varchar(50) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Estudiante] 
 ADD CONSTRAINT [PK_Estudiante]
	PRIMARY KEY CLUSTERED ([cif] ASC)
GO

ALTER TABLE [Expediente] 
 ADD CONSTRAINT [PK_Expediente]
	PRIMARY KEY CLUSTERED ([num] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Expediente] ADD CONSTRAINT [FK_Estudiante_Expediente]
	FOREIGN KEY ([cif]) REFERENCES [Estudiante] ([cif]) ON DELETE No Action ON UPDATE No Action
GO
