/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 01-oct-2025 16:12:02 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Prestamo_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Prestamo] DROP CONSTRAINT [FK_Prestamo_Cliente]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Prestamo]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Prestamo]
GO

/* Create Tables */

CREATE TABLE [Cliente]
(
	[cedula] nvarchar(16) NOT NULL,
	[direccion] nvarchar(max) NULL,
	[nombre] nvarchar(50) NULL
)
GO

CREATE TABLE [Prestamo]
(
	[num] int NOT NULL,
	[monto] money NULL,
	[fecha] date NULL,
	[cliente] nvarchar(16) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([cedula] ASC)
GO

ALTER TABLE [Prestamo] 
 ADD CONSTRAINT [PK_Prestamo]
	PRIMARY KEY CLUSTERED ([num] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Prestamo] ADD CONSTRAINT [FK_Prestamo_Cliente]
	FOREIGN KEY ([cliente]) REFERENCES [Cliente] ([cedula]) ON DELETE No Action ON UPDATE No Action
GO
